/* Copyright (c) 2016 Microsemi Corporation

   Permission is hereby granted, free of charge, to any person obtaining a copy
   of this software and associated documentation files (the "Software"), to deal
   in the Software without restriction, including without limitation the rights
   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
   copies of the Software, and to permit persons to whom the Software is
   furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in
   all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
   THE SOFTWARE.
*/

#ifndef _VTSS_OCELOT_REGS_DEVCPU_QS_H_
#define _VTSS_OCELOT_REGS_DEVCPU_QS_H_

#include "vtss_ocelot_regs_common.h"

#define VTSS_DEVCPU_QS_XTR_XTR_GRP_CFG(ri)   VTSS_IOREG(VTSS_TO_DEVCPU_QS,0x0 + (ri))
#define  VTSS_F_DEVCPU_QS_XTR_XTR_GRP_CFG_MODE(x)  VTSS_ENCODE_BITFIELD(x,2,2)
#define  VTSS_M_DEVCPU_QS_XTR_XTR_GRP_CFG_MODE     VTSS_ENCODE_BITMASK(2,2)
#define  VTSS_X_DEVCPU_QS_XTR_XTR_GRP_CFG_MODE(x)  VTSS_EXTRACT_BITFIELD(x,2,2)
#define  VTSS_F_DEVCPU_QS_XTR_XTR_GRP_CFG_STATUS_WORD_POS(x)  VTSS_ENCODE_BITFIELD(!!(x),1,1)
#define  VTSS_M_DEVCPU_QS_XTR_XTR_GRP_CFG_STATUS_WORD_POS  VTSS_BIT(1)
#define  VTSS_X_DEVCPU_QS_XTR_XTR_GRP_CFG_STATUS_WORD_POS(x)  VTSS_EXTRACT_BITFIELD(x,1,1)
#define  VTSS_F_DEVCPU_QS_XTR_XTR_GRP_CFG_BYTE_SWAP(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_DEVCPU_QS_XTR_XTR_GRP_CFG_BYTE_SWAP  VTSS_BIT(0)
#define  VTSS_X_DEVCPU_QS_XTR_XTR_GRP_CFG_BYTE_SWAP(x)  VTSS_EXTRACT_BITFIELD(x,0,1)

#define VTSS_DEVCPU_QS_XTR_XTR_RD(ri)        VTSS_IOREG(VTSS_TO_DEVCPU_QS,0x2 + (ri))
#define  VTSS_F_DEVCPU_QS_XTR_XTR_RD_DATA(x)  (x)
#define  VTSS_M_DEVCPU_QS_XTR_XTR_RD_DATA     0xffffffff
#define  VTSS_X_DEVCPU_QS_XTR_XTR_RD_DATA(x)  (x)

#define VTSS_DEVCPU_QS_XTR_XTR_FRM_PRUNING(ri)  VTSS_IOREG(VTSS_TO_DEVCPU_QS,0x4 + (ri))
#define  VTSS_F_DEVCPU_QS_XTR_XTR_FRM_PRUNING_PRUNE_SIZE(x)  VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_DEVCPU_QS_XTR_XTR_FRM_PRUNING_PRUNE_SIZE     VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_DEVCPU_QS_XTR_XTR_FRM_PRUNING_PRUNE_SIZE(x)  VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_DEVCPU_QS_XTR_XTR_FLUSH         VTSS_IOREG(VTSS_TO_DEVCPU_QS,0x6)
#define  VTSS_F_DEVCPU_QS_XTR_XTR_FLUSH_FLUSH(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_DEVCPU_QS_XTR_XTR_FLUSH_FLUSH     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_DEVCPU_QS_XTR_XTR_FLUSH_FLUSH(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_DEVCPU_QS_XTR_XTR_DATA_PRESENT  VTSS_IOREG(VTSS_TO_DEVCPU_QS,0x7)
#define  VTSS_F_DEVCPU_QS_XTR_XTR_DATA_PRESENT_DATA_PRESENT(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_DEVCPU_QS_XTR_XTR_DATA_PRESENT_DATA_PRESENT     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_DEVCPU_QS_XTR_XTR_DATA_PRESENT_DATA_PRESENT(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_DEVCPU_QS_XTR_XTR_CFG           VTSS_IOREG(VTSS_TO_DEVCPU_QS,0x8)
#define  VTSS_F_DEVCPU_QS_XTR_XTR_CFG_DP_WM(x)  VTSS_ENCODE_BITFIELD(x,5,3)
#define  VTSS_M_DEVCPU_QS_XTR_XTR_CFG_DP_WM     VTSS_ENCODE_BITMASK(5,3)
#define  VTSS_X_DEVCPU_QS_XTR_XTR_CFG_DP_WM(x)  VTSS_EXTRACT_BITFIELD(x,5,3)
#define  VTSS_F_DEVCPU_QS_XTR_XTR_CFG_SCH_WM(x)  VTSS_ENCODE_BITFIELD(x,2,3)
#define  VTSS_M_DEVCPU_QS_XTR_XTR_CFG_SCH_WM     VTSS_ENCODE_BITMASK(2,3)
#define  VTSS_X_DEVCPU_QS_XTR_XTR_CFG_SCH_WM(x)  VTSS_EXTRACT_BITFIELD(x,2,3)
#define  VTSS_F_DEVCPU_QS_XTR_XTR_CFG_OFLW_ERR_STICKY(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_DEVCPU_QS_XTR_XTR_CFG_OFLW_ERR_STICKY     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_DEVCPU_QS_XTR_XTR_CFG_OFLW_ERR_STICKY(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_DEVCPU_QS_INJ_INJ_GRP_CFG(ri)   VTSS_IOREG(VTSS_TO_DEVCPU_QS,0x9 + (ri))
#define  VTSS_F_DEVCPU_QS_INJ_INJ_GRP_CFG_MODE(x)  VTSS_ENCODE_BITFIELD(x,2,2)
#define  VTSS_M_DEVCPU_QS_INJ_INJ_GRP_CFG_MODE     VTSS_ENCODE_BITMASK(2,2)
#define  VTSS_X_DEVCPU_QS_INJ_INJ_GRP_CFG_MODE(x)  VTSS_EXTRACT_BITFIELD(x,2,2)
#define  VTSS_F_DEVCPU_QS_INJ_INJ_GRP_CFG_BYTE_SWAP(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_DEVCPU_QS_INJ_INJ_GRP_CFG_BYTE_SWAP  VTSS_BIT(0)
#define  VTSS_X_DEVCPU_QS_INJ_INJ_GRP_CFG_BYTE_SWAP(x)  VTSS_EXTRACT_BITFIELD(x,0,1)

#define VTSS_DEVCPU_QS_INJ_INJ_WR(ri)        VTSS_IOREG(VTSS_TO_DEVCPU_QS,0xb + (ri))
#define  VTSS_F_DEVCPU_QS_INJ_INJ_WR_DATA(x)  (x)
#define  VTSS_M_DEVCPU_QS_INJ_INJ_WR_DATA     0xffffffff
#define  VTSS_X_DEVCPU_QS_INJ_INJ_WR_DATA(x)  (x)

#define VTSS_DEVCPU_QS_INJ_INJ_CTRL(ri)      VTSS_IOREG(VTSS_TO_DEVCPU_QS,0xd + (ri))
#define  VTSS_F_DEVCPU_QS_INJ_INJ_CTRL_GAP_SIZE(x)  VTSS_ENCODE_BITFIELD(x,21,4)
#define  VTSS_M_DEVCPU_QS_INJ_INJ_CTRL_GAP_SIZE     VTSS_ENCODE_BITMASK(21,4)
#define  VTSS_X_DEVCPU_QS_INJ_INJ_CTRL_GAP_SIZE(x)  VTSS_EXTRACT_BITFIELD(x,21,4)
#define  VTSS_F_DEVCPU_QS_INJ_INJ_CTRL_ABORT(x)  VTSS_ENCODE_BITFIELD(!!(x),20,1)
#define  VTSS_M_DEVCPU_QS_INJ_INJ_CTRL_ABORT  VTSS_BIT(20)
#define  VTSS_X_DEVCPU_QS_INJ_INJ_CTRL_ABORT(x)  VTSS_EXTRACT_BITFIELD(x,20,1)
#define  VTSS_F_DEVCPU_QS_INJ_INJ_CTRL_EOF(x)  VTSS_ENCODE_BITFIELD(!!(x),19,1)
#define  VTSS_M_DEVCPU_QS_INJ_INJ_CTRL_EOF    VTSS_BIT(19)
#define  VTSS_X_DEVCPU_QS_INJ_INJ_CTRL_EOF(x)  VTSS_EXTRACT_BITFIELD(x,19,1)
#define  VTSS_F_DEVCPU_QS_INJ_INJ_CTRL_SOF(x)  VTSS_ENCODE_BITFIELD(!!(x),18,1)
#define  VTSS_M_DEVCPU_QS_INJ_INJ_CTRL_SOF    VTSS_BIT(18)
#define  VTSS_X_DEVCPU_QS_INJ_INJ_CTRL_SOF(x)  VTSS_EXTRACT_BITFIELD(x,18,1)
#define  VTSS_F_DEVCPU_QS_INJ_INJ_CTRL_VLD_BYTES(x)  VTSS_ENCODE_BITFIELD(x,16,2)
#define  VTSS_M_DEVCPU_QS_INJ_INJ_CTRL_VLD_BYTES     VTSS_ENCODE_BITMASK(16,2)
#define  VTSS_X_DEVCPU_QS_INJ_INJ_CTRL_VLD_BYTES(x)  VTSS_EXTRACT_BITFIELD(x,16,2)

#define VTSS_DEVCPU_QS_INJ_INJ_STATUS        VTSS_IOREG(VTSS_TO_DEVCPU_QS,0xf)
#define  VTSS_F_DEVCPU_QS_INJ_INJ_STATUS_WMARK_REACHED(x)  VTSS_ENCODE_BITFIELD(x,4,2)
#define  VTSS_M_DEVCPU_QS_INJ_INJ_STATUS_WMARK_REACHED     VTSS_ENCODE_BITMASK(4,2)
#define  VTSS_X_DEVCPU_QS_INJ_INJ_STATUS_WMARK_REACHED(x)  VTSS_EXTRACT_BITFIELD(x,4,2)
#define  VTSS_F_DEVCPU_QS_INJ_INJ_STATUS_FIFO_RDY(x)  VTSS_ENCODE_BITFIELD(x,2,2)
#define  VTSS_M_DEVCPU_QS_INJ_INJ_STATUS_FIFO_RDY     VTSS_ENCODE_BITMASK(2,2)
#define  VTSS_X_DEVCPU_QS_INJ_INJ_STATUS_FIFO_RDY(x)  VTSS_EXTRACT_BITFIELD(x,2,2)
#define  VTSS_F_DEVCPU_QS_INJ_INJ_STATUS_INJ_IN_PROGRESS(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_DEVCPU_QS_INJ_INJ_STATUS_INJ_IN_PROGRESS     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_DEVCPU_QS_INJ_INJ_STATUS_INJ_IN_PROGRESS(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_DEVCPU_QS_INJ_INJ_ERR(ri)       VTSS_IOREG(VTSS_TO_DEVCPU_QS,0x10 + (ri))
#define  VTSS_F_DEVCPU_QS_INJ_INJ_ERR_ABORT_ERR_STICKY(x)  VTSS_ENCODE_BITFIELD(!!(x),1,1)
#define  VTSS_M_DEVCPU_QS_INJ_INJ_ERR_ABORT_ERR_STICKY  VTSS_BIT(1)
#define  VTSS_X_DEVCPU_QS_INJ_INJ_ERR_ABORT_ERR_STICKY(x)  VTSS_EXTRACT_BITFIELD(x,1,1)
#define  VTSS_F_DEVCPU_QS_INJ_INJ_ERR_WR_ERR_STICKY(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_DEVCPU_QS_INJ_INJ_ERR_WR_ERR_STICKY  VTSS_BIT(0)
#define  VTSS_X_DEVCPU_QS_INJ_INJ_ERR_WR_ERR_STICKY(x)  VTSS_EXTRACT_BITFIELD(x,0,1)

#define VTSS_DEVCPU_QS_INJ_VTSS_DBG          VTSS_IOREG(VTSS_TO_DEVCPU_QS,0x12)
#define  VTSS_F_DEVCPU_QS_INJ_VTSS_DBG_FRM_CNT(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_DEVCPU_QS_INJ_VTSS_DBG_FRM_CNT     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_DEVCPU_QS_INJ_VTSS_DBG_FRM_CNT(x)  VTSS_EXTRACT_BITFIELD(x,0,4)


#endif /* _VTSS_OCELOT_REGS_DEVCPU_QS_H_ */
