/* Copyright (c) 2015 Microsemi Corporation

   Permission is hereby granted, free of charge, to any person obtaining a copy
   of this software and associated documentation files (the "Software"), to deal
   in the Software without restriction, including without limitation the rights
   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
   copies of the Software, and to permit persons to whom the Software is
   furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in
   all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
   THE SOFTWARE.
*/

#ifndef _VTSS_SERVALT_REGS_DEVCPU_ORG_H_
#define _VTSS_SERVALT_REGS_DEVCPU_ORG_H_

/*
 *
 * VCore-III Register Definitions
 *
 */

#include "vtss_servalt_regs_common.h"

#define VTSS_DEVCPU_ORG_ORG_IF_CTRL          VTSS_IOREG(VTSS_TO_DEVCPU_ORG,0x0)
#define  VTSS_F_DEVCPU_ORG_ORG_IF_CTRL_IF_CTRL(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_DEVCPU_ORG_ORG_IF_CTRL_IF_CTRL     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_DEVCPU_ORG_ORG_IF_CTRL_IF_CTRL(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_DEVCPU_ORG_ORG_IF_CFGSTAT       VTSS_IOREG(VTSS_TO_DEVCPU_ORG,0x1)
#define  VTSS_F_DEVCPU_ORG_ORG_IF_CFGSTAT_IF_NUM(x)  VTSS_ENCODE_BITFIELD(x,24,8)
#define  VTSS_M_DEVCPU_ORG_ORG_IF_CFGSTAT_IF_NUM     VTSS_ENCODE_BITMASK(24,8)
#define  VTSS_X_DEVCPU_ORG_ORG_IF_CFGSTAT_IF_NUM(x)  VTSS_EXTRACT_BITFIELD(x,24,8)
#define  VTSS_F_DEVCPU_ORG_ORG_IF_CFGSTAT_IF_STAT(x)  VTSS_ENCODE_BITFIELD(!!(x),16,1)
#define  VTSS_M_DEVCPU_ORG_ORG_IF_CFGSTAT_IF_STAT  VTSS_BIT(16)
#define  VTSS_X_DEVCPU_ORG_ORG_IF_CFGSTAT_IF_STAT(x)  VTSS_EXTRACT_BITFIELD(x,16,1)
#define  VTSS_F_DEVCPU_ORG_ORG_IF_CFGSTAT_IF_CFG(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_DEVCPU_ORG_ORG_IF_CFGSTAT_IF_CFG     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_DEVCPU_ORG_ORG_IF_CFGSTAT_IF_CFG(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_DEVCPU_ORG_ORG_ORG_CFG          VTSS_IOREG(VTSS_TO_DEVCPU_ORG,0x2)
#define  VTSS_F_DEVCPU_ORG_ORG_ORG_CFG_BLOCKING_ENA(x)  VTSS_ENCODE_BITFIELD(!!(x),2,1)
#define  VTSS_M_DEVCPU_ORG_ORG_ORG_CFG_BLOCKING_ENA  VTSS_BIT(2)
#define  VTSS_X_DEVCPU_ORG_ORG_ORG_CFG_BLOCKING_ENA(x)  VTSS_EXTRACT_BITFIELD(x,2,1)
#define  VTSS_F_DEVCPU_ORG_ORG_ORG_CFG_DROP_MODE_ENA(x)  VTSS_ENCODE_BITFIELD(!!(x),1,1)
#define  VTSS_M_DEVCPU_ORG_ORG_ORG_CFG_DROP_MODE_ENA  VTSS_BIT(1)
#define  VTSS_X_DEVCPU_ORG_ORG_ORG_CFG_DROP_MODE_ENA(x)  VTSS_EXTRACT_BITFIELD(x,1,1)
#define  VTSS_F_DEVCPU_ORG_ORG_ORG_CFG_FAST_WR(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_DEVCPU_ORG_ORG_ORG_CFG_FAST_WR  VTSS_BIT(0)
#define  VTSS_X_DEVCPU_ORG_ORG_ORG_CFG_FAST_WR(x)  VTSS_EXTRACT_BITFIELD(x,0,1)

#define VTSS_DEVCPU_ORG_ORG_ERR_CNTS         VTSS_IOREG(VTSS_TO_DEVCPU_ORG,0x3)
#define  VTSS_F_DEVCPU_ORG_ORG_ERR_CNTS_ERR_TGT_BUSY(x)  VTSS_ENCODE_BITFIELD(x,16,4)
#define  VTSS_M_DEVCPU_ORG_ORG_ERR_CNTS_ERR_TGT_BUSY     VTSS_ENCODE_BITMASK(16,4)
#define  VTSS_X_DEVCPU_ORG_ORG_ERR_CNTS_ERR_TGT_BUSY(x)  VTSS_EXTRACT_BITFIELD(x,16,4)
#define  VTSS_F_DEVCPU_ORG_ORG_ERR_CNTS_ERR_WD_DROP_ORG(x)  VTSS_ENCODE_BITFIELD(x,12,4)
#define  VTSS_M_DEVCPU_ORG_ORG_ERR_CNTS_ERR_WD_DROP_ORG     VTSS_ENCODE_BITMASK(12,4)
#define  VTSS_X_DEVCPU_ORG_ORG_ERR_CNTS_ERR_WD_DROP_ORG(x)  VTSS_EXTRACT_BITFIELD(x,12,4)
#define  VTSS_F_DEVCPU_ORG_ORG_ERR_CNTS_ERR_WD_DROP(x)  VTSS_ENCODE_BITFIELD(x,8,4)
#define  VTSS_M_DEVCPU_ORG_ORG_ERR_CNTS_ERR_WD_DROP     VTSS_ENCODE_BITMASK(8,4)
#define  VTSS_X_DEVCPU_ORG_ORG_ERR_CNTS_ERR_WD_DROP(x)  VTSS_EXTRACT_BITFIELD(x,8,4)
#define  VTSS_F_DEVCPU_ORG_ORG_ERR_CNTS_ERR_NO_ACTION(x)  VTSS_ENCODE_BITFIELD(x,4,4)
#define  VTSS_M_DEVCPU_ORG_ORG_ERR_CNTS_ERR_NO_ACTION     VTSS_ENCODE_BITMASK(4,4)
#define  VTSS_X_DEVCPU_ORG_ORG_ERR_CNTS_ERR_NO_ACTION(x)  VTSS_EXTRACT_BITFIELD(x,4,4)
#define  VTSS_F_DEVCPU_ORG_ORG_ERR_CNTS_ERR_UTM(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_DEVCPU_ORG_ORG_ERR_CNTS_ERR_UTM     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_DEVCPU_ORG_ORG_ERR_CNTS_ERR_UTM(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_DEVCPU_ORG_ORG_TIMEOUT_CFG      VTSS_IOREG(VTSS_TO_DEVCPU_ORG,0x4)
#define  VTSS_F_DEVCPU_ORG_ORG_TIMEOUT_CFG_TIMEOUT_CFG(x)  VTSS_ENCODE_BITFIELD(x,0,12)
#define  VTSS_M_DEVCPU_ORG_ORG_TIMEOUT_CFG_TIMEOUT_CFG     VTSS_ENCODE_BITMASK(0,12)
#define  VTSS_X_DEVCPU_ORG_ORG_TIMEOUT_CFG_TIMEOUT_CFG(x)  VTSS_EXTRACT_BITFIELD(x,0,12)

#define VTSS_DEVCPU_ORG_ORG_GPR              VTSS_IOREG(VTSS_TO_DEVCPU_ORG,0x5)
#define  VTSS_F_DEVCPU_ORG_ORG_GPR_GPR(x)     (x)
#define  VTSS_M_DEVCPU_ORG_ORG_GPR_GPR        0xffffffff
#define  VTSS_X_DEVCPU_ORG_ORG_GPR_GPR(x)     (x)

#define VTSS_DEVCPU_ORG_ORG_MAILBOX_SET      VTSS_IOREG(VTSS_TO_DEVCPU_ORG,0x6)
#define  VTSS_F_DEVCPU_ORG_ORG_MAILBOX_SET_MAILBOX_SET(x)  (x)
#define  VTSS_M_DEVCPU_ORG_ORG_MAILBOX_SET_MAILBOX_SET     0xffffffff
#define  VTSS_X_DEVCPU_ORG_ORG_MAILBOX_SET_MAILBOX_SET(x)  (x)

#define VTSS_DEVCPU_ORG_ORG_MAILBOX_CLR      VTSS_IOREG(VTSS_TO_DEVCPU_ORG,0x7)
#define  VTSS_F_DEVCPU_ORG_ORG_MAILBOX_CLR_MAILBOX_CLR(x)  (x)
#define  VTSS_M_DEVCPU_ORG_ORG_MAILBOX_CLR_MAILBOX_CLR     0xffffffff
#define  VTSS_X_DEVCPU_ORG_ORG_MAILBOX_CLR_MAILBOX_CLR(x)  (x)

#define VTSS_DEVCPU_ORG_ORG_MAILBOX          VTSS_IOREG(VTSS_TO_DEVCPU_ORG,0x8)
#define  VTSS_F_DEVCPU_ORG_ORG_MAILBOX_MAILBOX(x)  (x)
#define  VTSS_M_DEVCPU_ORG_ORG_MAILBOX_MAILBOX     0xffffffff
#define  VTSS_X_DEVCPU_ORG_ORG_MAILBOX_MAILBOX(x)  (x)

#define VTSS_DEVCPU_ORG_ORG_SEMA_CFG         VTSS_IOREG(VTSS_TO_DEVCPU_ORG,0x9)
#define  VTSS_F_DEVCPU_ORG_ORG_SEMA_CFG_SEMA_INTR_POL(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_DEVCPU_ORG_ORG_SEMA_CFG_SEMA_INTR_POL     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_DEVCPU_ORG_ORG_SEMA_CFG_SEMA_INTR_POL(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_DEVCPU_ORG_ORG_SEMA0            VTSS_IOREG(VTSS_TO_DEVCPU_ORG,0xa)
#define  VTSS_F_DEVCPU_ORG_ORG_SEMA0_SEMA0(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_DEVCPU_ORG_ORG_SEMA0_SEMA0    VTSS_BIT(0)
#define  VTSS_X_DEVCPU_ORG_ORG_SEMA0_SEMA0(x)  VTSS_EXTRACT_BITFIELD(x,0,1)

#define VTSS_DEVCPU_ORG_ORG_SEMA0_OWNER      VTSS_IOREG(VTSS_TO_DEVCPU_ORG,0xb)
#define  VTSS_F_DEVCPU_ORG_ORG_SEMA0_OWNER_SEMA0_OWNER(x)  (x)
#define  VTSS_M_DEVCPU_ORG_ORG_SEMA0_OWNER_SEMA0_OWNER     0xffffffff
#define  VTSS_X_DEVCPU_ORG_ORG_SEMA0_OWNER_SEMA0_OWNER(x)  (x)

#define VTSS_DEVCPU_ORG_ORG_SEMA1            VTSS_IOREG(VTSS_TO_DEVCPU_ORG,0xc)
#define  VTSS_F_DEVCPU_ORG_ORG_SEMA1_SEMA1(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_DEVCPU_ORG_ORG_SEMA1_SEMA1    VTSS_BIT(0)
#define  VTSS_X_DEVCPU_ORG_ORG_SEMA1_SEMA1(x)  VTSS_EXTRACT_BITFIELD(x,0,1)

#define VTSS_DEVCPU_ORG_ORG_SEMA1_OWNER      VTSS_IOREG(VTSS_TO_DEVCPU_ORG,0xd)
#define  VTSS_F_DEVCPU_ORG_ORG_SEMA1_OWNER_SEMA1_OWNER(x)  (x)
#define  VTSS_M_DEVCPU_ORG_ORG_SEMA1_OWNER_SEMA1_OWNER     0xffffffff
#define  VTSS_X_DEVCPU_ORG_ORG_SEMA1_OWNER_SEMA1_OWNER(x)  (x)


#endif /* _VTSS_SERVALT_REGS_DEVCPU_ORG_H_ */
