# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_FIREANT) += fireant_pcb125.dtb
dtb-$(CONFIG_ARCH_FIREANT) += fireant_pcb134.dtb fireant_pcb134_emmc.dtb
dtb-$(CONFIG_ARCH_FIREANT) += fireant_pcb135.dtb fireant_pcb135_emmc.dtb
