#
# Makefile for the Vitesse Semiconductor network device drivers.
#

obj-$(CONFIG_VC3FDMA) += vc3fdma.o

obj-$(CONFIG_VC3MUX)  += vtss_if_mux.o

vtss_if_mux-y := vtss_if_mux_main.o vtss_if_mux_dev.o vtss_if_mux_netlink.o
